### ISSUE TITLE
fix web10 login on old macs

### ISSUE THREAD

**Issue by jacoby149** [jacoby149/web10#34]
old macs refuse to connect to the mongo atlas DB

**Comment by jacoby149** [comment]
nginx-proxy_1  | nginx.1     | auth.localhost 172.19.0.1 - - [27/Jul/2022:22:16:25 +0000] "GET /sockjs-node/info?t=1658960185264 HTTP/1.1" 200 90 "http://auth.localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/[103.0.0.0](http://103.0.0.0/) Safari/537.36" "[172.19.0.9:80](http://172.19.0.9/)"

nginx-proxy_1  | nginx.1     | auth.localhost 172.19.0.1 - - [27/Jul/2022:22:16:25 +0000] "GET /favicon.ico HTTP/1.1" 304 0 "http://auth.localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/[103.0.0.0](http://103.0.0.0/) Safari/537.36" "[172.19.0.9:80](http://172.19.0.9/)"

api_1          | INFO:     [172.19.0.5:42410](http://172.19.0.5:42410/) - "POST /signup HTTP/1.1" 500 Internal Server Error

api_1          | ERROR:    Exception in ASGI application

api_1          | Traceback (most recent call last):

api_1          |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi

api_1          |     result = await app(self.scope, self.receive, self.send)

api_1          |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__

api_1          |     return await [self.app](http://self.app/)(scope, receive, send)

api_1          |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__

api_1          |     await super().__call__(scope, receive, send)

api_1          |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__

api_1          |     await self.middleware_stack(scope, receive, send)

api_1          |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__

api_1          |     raise exc from None

api_1          |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__

api_1          |     await [self.app](http://self.app/)(scope, receive, _send)

api_1          |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__

api_1          |     await self.simple_response(scope, receive, send, request_headers=headers)

api_1          |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response

api_1          |     await [self.app](http://self.app/)(scope, receive, send)

api_1          |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__

api_1          |     raise exc from None

api_1          |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__

api_1          |     await [self.app](http://self.app/)(scope, receive, sender)

api_1          |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__

api_1          |     await route.handle(scope, receive, send)

api_1          |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle

api_1          |     await [self.app](http://self.app/)(scope, receive, send)

api_1          |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 52, in app

api_1          |     response = await func(request)

api_1          |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app

api_1          |     raw_response = await run_endpoint_function(

api_1          |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function

api_1          |     return await dependant.call(**values)

api_1          |   File "/web10/./app/main.py", line 369, in signup

api_1          |     res = db.create_user(form_data, get_password_hash)

api_1          |   File "/web10/./app/mongo.py", line 163, in create_user

api_1          |     if get_star(username):

api_1          |   File "/web10/./app/mongo.py", line 134, in get_star

api_1          |     return get_term_record(user, "*")

api_1          |   File "/web10/./app/mongo.py", line 127, in get_term_record

api_1          |     record = db[f"{username}"].find_one(query)

api_1          |   File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 1452, in find_one

api_1          |     for result in cursor.limit(-1):

api_1          |   File "/usr/local/lib/python3.9/site-packages/pymongo/cursor.py", line 1248, in next

api_1          |     if len(self.__data) or self._refresh():

api_1          |   File "/usr/local/lib/python3.9/site-packages/pymongo/cursor.py", line 1139, in _refresh

api_1          |     self.__session = self.__collection.database.client._ensure_session()

api_1          |   File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1712, in _ensure_session

api_1          |     return self.__start_session(True, causal_consistency=False)

api_1          |   File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1657, in __start_session

api_1          |     self._topology._check_implicit_session_support()

api_1          |   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support

api_1          |     self._check_session_support()

api_1          |   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 554, in _check_session_support

api_1          |     self._select_servers_loop(

api_1          |   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 238, in _select_servers_loop

api_1          |     raise ServerSelectionTimeoutError(

api_1          | pymongo.errors.ServerSelectionTimeoutError: [cluster1-shard-00-00.alxkz.mongodb.net:27017](http://cluster1-shard-00-00.alxkz.mongodb.net:27017/): timed out,[cluster1-shard-00-01.alxkz.mongodb.net:27017](http://cluster1-shard-00-01.alxkz.mongodb.net:27017/): timed out,[cluster1-shard-00-02.alxkz.mongodb.net:27017](http://cluster1-shard-00-02.alxkz.mongodb.net:27017/): timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 62e1b90fb9720795020679be, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('[cluster1-shard-00-00.alxkz.mongodb.net](http://cluster1-shard-00-00.alxkz.mongodb.net/)', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('[cluster1-shard-00-00.alxkz.mongodb.net:27017](http://cluster1-shard-00-00.alxkz.mongodb.net:27017/): timed out')>, <ServerDescription ('[cluster1-shard-00-01.alxkz.mongodb.net](http://cluster1-shard-00-01.alxkz.mongodb.net/)', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('[cluster1-shard-00-01.alxkz.mongodb.net:27017](http://cluster1-shard-00-01.alxkz.mongodb.net:27017/): timed out')>, <ServerDescription ('[cluster1-shard-00-02.alxkz.mongodb.net](http://cluster1-shard-00-02.alxkz.mongodb.net/)', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('[cluster1-shard-00-02.alxkz.mongodb.net:27017](http://cluster1-shard-00-02.alxkz.mongodb.net:27017/): timed out')>]>
